# Generated by Django 2.2.3 on 2019-07-22 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='image',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='game',
            name='key',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
